"""empty message

Revision ID: bb589ebb708e
Revises: 
Create Date: 2020-06-19 15:57:46.095180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb589ebb708e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=True),
    sa.Column('dealer', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.String(length=200), nullable=True),
    sa.Column('comments', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
